//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiem
    {
        public int idbangDiem { get; set; }
        public string idmonHoc { get; set; }
        public Nullable<int> idhocSinh { get; set; }
        public Nullable<int> diem { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
