//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangdiemh
    {
        public int id { get; set; }
        public Nullable<int> idhs { get; set; }
        public Nullable<int> toan { get; set; }
        public Nullable<int> ly { get; set; }
        public Nullable<int> hoa { get; set; }
        public Nullable<int> sinh { get; set; }
        public Nullable<int> van { get; set; }
        public Nullable<int> su { get; set; }
        public Nullable<int> dia { get; set; }
        public Nullable<int> gdcd { get; set; }
        public Nullable<int> tin { get; set; }
    
        public virtual hocsinh hocsinh { get; set; }
    }
}
