//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int idbangdiem { get; set; }
        public string idmon { get; set; }
        public Nullable<int> idhocsinh { get; set; }
        public Nullable<int> diem1 { get; set; }
    
        public virtual hocsinh hocsinh { get; set; }
        public virtual monhoc monhoc { get; set; }
    }
}
