//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        public int id { get; set; }
        public Nullable<int> idhocSinh { get; set; }
        public string tenlop { get; set; }
        public Nullable<int> idchuNhiem { get; set; }
        public string nienkhoa { get; set; }
        public Nullable<int> hocki { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
